name: Deploy

on:
  push:
    branches:
      - 'master'
    tags:
      - "v**"

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      run: npm ci

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
